Friends integrity with 2 rows.
Meltrust/stay-in-touch pull request #3
Opened 2021-05-23 05:46 UTC by Meltrust

In this milestone I:

    Reviewed and created models for the project requirements.
    Added helper methods for the mirrored friendships in the 2-row context.
    Updated models, controllers, and helpers.
    Followed the git-flow rules.
    Encapsulated the code in classes and objects.
    Delivered the project with an organized folder structure.
    Updated gems
    Used the simplest solutions as possible, over the most complex ones. Readability above all was always the goal.
    Working alone, as my former partner got sick.

Notice:  After the last milestone, I forgot to merge.  After realizing this, I had to merge so some of my commits are on the last merge.  In order to preserve integrity, I had to continue in this same branch instead of creating another one.  Won't happen again.  Thanks.

Thanks for the review!

2021-05-23 07:16 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- User can send friendship request :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)) and when friendship is confirmed, an additional row with reversed user-friend pair is created
```
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [ ] thanks to this, we can find user friends only by user_id in friendships table
```
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

- [ ] User#pending_friends can be defined as association with `SQL query instead of processing objects in application memory` (as the database was created to store and query data it is always more efficient than ruby)
```
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend


```

- [ ] User#friend_requests can be defined as association with `SQL query instead of processing objects in application memory` (as the database was created to store and query data it is always more efficient than ruby)
```
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships

```

- [ ] in order to get all posts written by user on their friends, students can use simple method in User model (in order to **NOT** do it with Enumerables)
```
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

- [ ] Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

- [ ] Please add more unit tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))

Nice to have [OPTIONAL] :

- [ ] It will be nice if you put all logic in your view inside helper.
- [ ] Please read about n+1 and make sure there are no n + 1 queries in index views [Recommended article.](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5)

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-05-23 07:16 UTC, rindrajosia commented on app/models/user.rb
> +  # has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/models/user.rb
> +    # friends_array += inverse_friendships.map { |friendship| friendship.user if friendship.confirmed }
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/models/user.rb
> +    # inverse_friendships.map { |friendship| friendship.user unless friendship.confirmed }.compact
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/models/user.rb
> +    # friendship = inverse_friendships.find { |my_friendship| my_friendship.user == user }
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/models/user.rb
> +    # friendship = inverse_friendships.find { |my_friendship| my_friendship.user == user }
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/models/friendship.rb
> +    # Friendship.create(user: user, friend: friend, confirmed: nil)
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/helpers/application_helper.rb
> +    # link_to('Reject?', user_friendship_path(user_id: friendship.id), method: :delete, class: 'profile-link')
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/helpers/application_helper.rb
> +    # link_to('Accept?', user_friendship_path(user_id: friendship.id), method: :put, class: 'profile-link')
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-23 07:16 UTC, rindrajosia commented on app/controllers/friendships_controller.rb
> +    # friend = User.find(params[:user_id])
Inline comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

2021-05-30 12:52 UTC, oloomoses approved these changes
Hello @Meltrust,
**Well done on implementing the changes suggested by the @rindrajosia**
### Highlights
- An additional row is created on inverse friendship :heavy_check_mark:
- Unit and integration tests :heavy_check_mark:
- Descriptive pr :heavy_check_mark:
- Linters and rubocop configuration :heavy_check_mark:

**This milestone meets all the requirements and therefore:**
## Approved :tada: :muscle: :clap:
Congratulations and best wishes on the next milestone. 

#### Happy coding
_slack: Oloo Moses_

2021-05-30 12:58 UTC, merged